### PR TITLE
git submodules updated

### PR DESCRIPTION
**Pull request by Samantha-uk**
Updated submodules, main intent to pull in PawPaw changes to support changed linker options on newer MacOS builds.

Submodule path 'src/PawPaw': checked out '45aa5eef69da8aee1bc9385f8381107031c7655e'
Submodule path 'src/mod-app-asio': checked out '34e9bd655ebaabb63bc9d182a6d0e7d0a291f7d7'
Submodule path 'src/mod-ui': checked out 'c5e4f5d10cfd5d696b99ee338598948527f7f11b'

### CODE REVIEW

**Comment by falkTX** [comment]
the mod-app-asio one is wrong, points to the wrong commit. it shouldnt update anyway as it is not used on macOS.
mod-ui also does not need an update yet, the change there was for something we do not use so we dont need to update it.

**Comment by Samantha-uk** [comment]
I _think_ I've now reverted so just the PawPaw submodule is updated.

**Comment by Samantha-uk** [comment]
Ooops!
I modified build.yml on my fork so I could trigger the workflow manually, I didn't realise this would get pulled into the PR; now reverted.

**Comment by falkTX** [comment]
PRs with CI workflows in them need to be approved manually until at least 1 PR from that author is merged.
the next PRs should have CI run automatically

**Comment by falkTX** [comment]
I see this is fine now, thanks

**Comment by Samantha-uk** [comment]
Sorry it was a bit of a mess!

**Pull request merged**
